import { env } from '@env'
import configPromise from '@payload-config'
import type { Metadata, Viewport } from 'next'
import { unstable_cache } from 'next/cache'
import { Outfit } from 'next/font/google'
import { getPayload } from 'payload'
import { ReactNode } from 'react'

import GoogleAdsense from '@/components/GoogleAdsense'
import GoogleAnalytics from '@/components/GoogleAnalytics'
import { colors } from '@/lib/theme'
import Provider from '@/trpc/Provider'

import './globals.css'

const outfit = Outfit({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  preload: true,
  adjustFontFallback: false,
})

export const viewport: Viewport = {
  themeColor: colors.primary,
}

const getCachedSiteSettings = unstable_cache(
  async () => {
    const payload = await getPayload({
      config: configPromise,
    })

    const data = await payload.findGlobal({
      slug: 'site-settings',
      draft: false,
    })

    return data
  },
  ['site-settings'],
  { tags: ['site-settings'] },
)

export async function generateMetadata(): Promise<Metadata> {
  try {
    // calling the site-settings to get all the data
    const metadata = await getCachedSiteSettings()
    const generalSettings = metadata?.general

    const ogImageUrl =
      typeof generalSettings?.ogImageUrl === 'object'
        ? generalSettings?.ogImageUrl?.url!
        : '/images/seed/og-image.png'

    const title = {
      default: generalSettings?.title,
      template: `%s | ${generalSettings?.title}`,
    }

    const description = generalSettings?.description
    const ogImage = [
      {
        url: `${ogImageUrl}`,
        height: 630,
        width: 1200,
        alt: `og image`,
      },
    ]

    return {
      title,
      description,
      // we're appending the http|https int the env variable
      metadataBase: env.PAYLOAD_URL as unknown as URL,
      openGraph: {
        title,
        description,
        images: ogImage,
      },
      twitter: {
        title,
        description,
        images: ogImage,
      },
      keywords: generalSettings?.keywords,
    }
  } catch (error) {
    // in error case returning a base metadata object
    console.log({ error })

    return {
      title: 'Create CQL App',
      description: 'Generated by create cql app',
    }
  }
}

const RootLayout = async ({ children }: { children: ReactNode }) => {
  const metadata = await getCachedSiteSettings()
  const generalSettings = metadata?.general

  const faviconUrl =
    typeof generalSettings?.faviconUrl === 'object'
      ? generalSettings?.faviconUrl?.url!
      : '/favicon.ico'
  return (
    <html lang='en'>
      <head>
        <link rel='icon' type='image/x-icon' href={faviconUrl} />

        <GoogleAdsense metadata={metadata} />
        <GoogleAnalytics metadata={metadata} />
      </head>
      <body className={outfit.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  )
}

export default RootLayout
